behaviors:
  DrunkAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
        learning_rate: 3.0e-4
    keep_checkpoints: 5
    max_steps: 200000000
    time_horizon: 128
    summary_freq: 20000
    threaded: true
environment_parameters :
  train_speed :
    curriculum :
      - name : Lesson0 # This is the start of the second lesson
        completion_criteria:
          measure : reward
          behavior : DrunkAgent
          signal_smoothing : true
          min_lesson_length : 100
          threshold : 3.2
        value :
          sampler_type : uniform
          sampler_parameters :
            min_value : 1.0
            max_value : 5.0
      - name : Lesson1
        completion_criteria :
          measure : reward
          behavior : DrunkAgent
          signal_smoothing : true
          min_lesson_length : 100
          threshold : 3.2
        value :
          sampler_type : uniform
          sampler_parameters :
            min_value : 5.0
            max_value : 15.0
      - name : Lesson2
        completion_criteria :
          measure : reward
          behavior : DrunkAgent
          signal_smoothing : true
          min_lesson_length : 100
          threshold : 3.2
        value :
          sampler_type : uniform
          sampler_parameters :
            min_value : 15.0
            max_value : 30.0
      - name : Lesson3
        completion_criteria :
          measure : reward
          behavior : DrunkAgent
          signal_smoothing : true
          min_lesson_length : 100
          threshold : 3.2
        value :
          sampler_type : uniform
          sampler_parameters :
            min_value : 30.0
            max_value : 50.0
      - name : Lesson4
        value : 30.0
